markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
encoding: utf-8

# Setup
title:            Aaron Stevens
tagline:          'a blog'
description:      Aaron Stevens' work-related journal of the I.T. world. Yes, I'm available for hire.

# 'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

url:              http://aaronstevens.co.uk

author:
  name:           'Aaron Stevens'
  url:            https://twitter.com/aaronstevens_

github:
repo: https://github.com/aaronstevens

gems:
  - jekyll-mentions
