# Site settings
title: Aaron Stevens
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog, CV stuff, to be decided!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aaronstevens.co.uk" # the base hostname & protocol for your site
twitter_username: aaronstevens_
github_username:  aaronstevens

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
encoding: utf-8
